### ISSUE TITLE
Program window is to big 

### ISSUE THREAD

**Issue by 3835** [CroatianMeteorNetwork/cmn_binviewer#3]
Hi!
I have strange problem with CMN binViewer. The program window does not fit on the desktop (
please take a look at screenshots). The part responsible for writing is cut off. 

Screenshots
https://i.imgur.com/nkrLPKo.png
https://i.imgur.com/gr4cAvu.png

My spec:
- desktop resolution is 1366x768, 
- Windows 7 Professional with Service Pack 1, 64bit
- graphics card Intel HD Graphics 3000

I tried 32 and 64bit version, the effect is the same.

**Comment by dvida** [comment]
Hi,
the 64-bit version has the option to resize the image. Look for 'Resize' in the toolbar (I can see it in your screenshots). Then just refresh the image and that's it!
And looking at the screenshots, it seems that everything fits otherwise. Some time in the future I will add finer resize steps, but this is good enough for now.

Let me know if you have solved the issue!

**Comment by 3835** [comment]
I thought the resize would change the size of the "photo". Now works fine! 
Thanks a lot!
